### ISSUE TITLE
Error when Running `yarn install`

### ISSUE THREAD

**Issue by SharkJ** [theia-ide/theia-xtext#8]
Hi,
I'm following your theia-extension Readme and trying to make it work in my PC.
So far, I have succeeded in cloning the repo and building the shadowJar. However, when I go back to the root directory (theia-xtext folder) and execute `yarn install` as you have mentioned in the Readme, I get the following output in my command line: -

```

yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["rimraf@latest"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-rimraf-2.6.2-2ed8150d24a16ea8651e6d6ef0f47c4158ce7a36\\node_modules\\rimraf" as pattern ["rimraf@^2.6.1","rimraf@^2.2.8","rimraf@^2.2.8","rimraf@^2.5.4","rimraf@2","rimraf@^2.6.1","rimraf@^2.6.2","rimraf@2","rimraf@^2.5.4","rimraf@^2.5.4","rimraf@^2.6.1","rimraf@^2.5.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/editor@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-editor-0.4.0-next.d11a5b63-dc05a824886d230f003b180142ca0d904dab19ab\\node_modules\\@theia\\editor" as pattern ["@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/filesystem@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-filesystem-0.4.0-next.d11a5b63-89dfc682f5c9db8db52388a638a02676e9338cec\\node_modules\\@theia\\filesystem" as pattern ["@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/markers@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-markers-0.4.0-next.d11a5b63-134b1fb6f79fe604fd96901f9e8847c9887d077a\\node_modules\\@theia\\markers" as pattern ["@theia/markers@0.4.0-next.d11a5b63","@theia/markers@0.4.0-next.d11a5b63","@theia/markers@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/monaco@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-monaco-0.4.0-next.d11a5b63-2b1dc600c0f792123c11d2bf989889006fcdce04\\node_modules\\@theia\\monaco" as pattern ["@theia/monaco@0.4.0-next.d11a5b63","@theia/monaco@0.4.0-next.d11a5b63","@theia/monaco@0.4.0-next.d11a5b63","@theia/monaco@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/navigator@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-navigator-0.4.0-next.d11a5b63-3280ab0fbbb795217d680c902b5477936769d065\\node_modules\\@theia\\navigator" as pattern ["@theia/navigator@0.4.0-next.d11a5b63","@theia/navigator@0.4.0-next.d11a5b63","@theia/navigator@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/outline-view@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-outline-view-0.4.0-next.d11a5b63-56d1c8990b5b8a15752776c6d5a290b896272711\\node_modules\\@theia\\outline-view" as pattern ["@theia/outline-view@0.4.0-next.d11a5b63","@theia/outline-view@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/output@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-output-0.4.0-next.d11a5b63-b4a8e1a6c921debe907e7cb3f2442cc2537e99a6\\node_modules\\@theia\\output" as pattern ["@theia/output@0.4.0-next.d11a5b63","@theia/output@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/preferences@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-preferences-0.4.0-next.d11a5b63-6a89f37b72f51d89dcf85578b1185a6c92f00b5b\\node_modules\\@theia\\preferences" as pattern ["@theia/preferences@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/process@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-process-0.4.0-next.d11a5b63-6f657eabb0136399e62bd6701b2151c2ce3a7c7d\\node_modules\\@theia\\process" as pattern ["@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/terminal@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-terminal-0.4.0-next.d11a5b63-57db0260383bb4585aa408353ced636e10f4f89e\\node_modules\\@theia\\terminal" as pattern ["@theia/terminal@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/userstorage@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-userstorage-0.4.0-next.d11a5b63-a9d8b3d8d597d0fb044ae0c7e3ea53f1c0263851\\node_modules\\@theia\\userstorage" as pattern ["@theia/userstorage@0.4.0-next.d11a5b63","@theia/userstorage@0.4.0-next.d11a5b63","@theia/userstorage@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/workspace@next"] is trying to unpack in the same destination "C:\\Users\\shjslk\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@theia-workspace-0.4.0-next.d11a5b63-4bf1d242b8d88d0a540dc446fcfd5c301daf7da8\\node_modules\\@theia\\workspace" as pattern ["@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-2abbf8c4-aeef-472d-b672-98b20587b580 > browser-app > @theia/cli > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[4/4] Building fresh packages...
$ lerna run prepare
lerna info version 2.4.0
@theia/xtext-dsl-extension: > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext-dsl-extension
@theia/xtext-dsl-extension: > yarn run clean && yarn run build
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ rimraf lib
@theia/xtext-dsl-extension: Done in 0.36s.
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ tsc && yarn run copy-ls
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ rm -rf ./build && mkdir build && cp ../xtext-dsl-language-server/io.typefox.xtext.langserver.example.ide/build/libs/dsl-language-server.jar ./build
@theia/xtext-dsl-extension: 'rm' is not recognized as an internal or external command,
@theia/xtext-dsl-extension: operable program or batch file.
@theia/xtext-dsl-extension: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@theia/xtext-dsl-extension: error Command failed with exit code 1.
@theia/xtext-dsl-extension: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@theia/xtext-dsl-extension: error Command failed with exit code 1.
@theia/xtext-dsl-extension: npm ERR! code ELIFECYCLE
@theia/xtext-dsl-extension: npm ERR! errno 1
@theia/xtext-dsl-extension: npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run build`
@theia/xtext-dsl-extension: npm ERR! Exit status 1
@theia/xtext-dsl-extension: npm ERR!
@theia/xtext-dsl-extension: npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
@theia/xtext-dsl-extension: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@theia/xtext-dsl-extension: npm ERR! A complete log of this run can be found in:
@theia/xtext-dsl-extension: npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-21T05_47_31_867Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! 'rm' is not recognized as an internal or external command,
lerna ERR! operable program or batch file.
lerna ERR! error Command failed with exit code 1.
lerna ERR! error Command failed with exit code 1.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run build`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-21T05_47_31_867Z-debug.log
lerna ERR!
lerna ERR!
lerna ERR! > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext-dsl-extension
lerna ERR! > yarn run clean && yarn run build
lerna ERR!
lerna ERR! yarn run v1.12.3
lerna ERR! $ rimraf lib
lerna ERR! Done in 0.36s.
lerna ERR! yarn run v1.12.3
lerna ERR! $ tsc && yarn run copy-ls
lerna ERR! $ rm -rf ./build && mkdir build && cp ../xtext-dsl-language-server/io.typefox.xtext.langserver.example.ide/build/libs/dsl-language-server.jar ./build
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
(node:12084) UnhandledPromiseRejectionWarning: Error: Command failed: npm run prepare
warning package.json: No license field
warning package.json: No license field
warning package.json: No license field
'rm' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
error Command failed with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-21T05_47_31_867Z-debug.log


> @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext-dsl-extension
> yarn run clean && yarn run build

yarn run v1.12.3
$ rimraf lib
Done in 0.36s.
yarn run v1.12.3
$ tsc && yarn run copy-ls
$ rm -rf ./build && mkdir build && cp ../xtext-dsl-language-server/io.typefox.xtext.langserver.example.ide/build/libs/dsl-language-server.jar ./build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:12084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:12084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

Why do I get this error? How do I correct it? I would really appreciate it if you could let me know.

Thank You!

**Comment by kittaakos** [comment]
For the record:
```
lerna ERR! 'rm' is not recognized as an internal or external command,
```

This line
https://github.com/theia-ide/theia-xtext/blob/99847e5cb7bb6f0d01452e67a8b387f5646bb5f1/xtext-dsl-extension/package.json#L21

`rm` should be changed to `rimraf`. Otherwise, people on Windows cannot use the example.

**Comment by SharkJ** [comment]
Thank You @kittaakos! 
@svenefftinge  I've been making changes to the project in order to run it locally. The changes made were as suggested by @kittakos in [this issue](https://github.com/theia-ide/theia/issues/3564).
I get the below output now. Could you kindly help me correct it?

```

$ yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
$ lerna run prepare
lerna info version 2.4.0
@theia/xtext-dsl-extension: > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\
theia-xtext\xtext-dsl-extension
@theia/xtext-dsl-extension: > yarn run clean && yarn run build
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ rimraf lib
@theia/xtext-dsl-extension: Done in 0.28s.
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ tsc && yarn run copy-ls
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(30,12): error T
S2339: Property 'languages' does not exist on type 'typeof monaco'.
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(36,12): error T
S2339: Property 'languages' does not exist on type 'typeof monaco'.
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(52,12): error T
S2339: Property 'languages' does not exist on type 'typeof monaco'.
@theia/xtext-dsl-extension: info Visit https://yarnpkg.com/en/docs/cli/run for d
ocumentation about this command.
@theia/xtext-dsl-extension: error Command failed with exit code 2.
@theia/xtext-dsl-extension: npm ERR! code ELIFECYCLE
@theia/xtext-dsl-extension: npm ERR! errno 1
@theia/xtext-dsl-extension: npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `
yarn run clean && yarn run build`
@theia/xtext-dsl-extension: npm ERR! Exit status 1
@theia/xtext-dsl-extension: npm ERR!
@theia/xtext-dsl-extension: npm ERR! Failed at the @theia/xtext-dsl-extension@0.
1.0 prepare script.
@theia/xtext-dsl-extension: npm ERR! This is probably not a problem with npm. Th
ere is likely additional logging output above.
@theia/xtext-dsl-extension: npm ERR! A complete log of this run can be found in:
@theia/xtext-dsl-extension: npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cac
he\_logs\2018-11-21T09_31_50_614Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! error Command failed with exit code 2.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean &&
 yarn run build`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare scrip
t.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely add
itional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-
21T09_31_50_614Z-debug.log
lerna ERR!
lerna ERR!
lerna ERR! > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext
-dsl-extension
lerna ERR! > yarn run clean && yarn run build
lerna ERR!
lerna ERR! yarn run v1.12.3
lerna ERR! $ rimraf lib
lerna ERR! Done in 0.28s.
lerna ERR! yarn run v1.12.3
lerna ERR! $ tsc && yarn run copy-ls
lerna ERR! src/browser/language-contribution.ts(30,12): error TS2339: Property '
languages' does not exist on type 'typeof monaco'.
lerna ERR! src/browser/language-contribution.ts(36,12): error TS2339: Property '
languages' does not exist on type 'typeof monaco'.
lerna ERR! src/browser/language-contribution.ts(52,12): error TS2339: Property '
languages' does not exist on type 'typeof monaco'.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation abou
t this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\
index.js:236:11)
lerna ERR!     at <anonymous>
(node:5572) UnhandledPromiseRejectionWarning: Error: Command failed: npm run pre
pare
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run b
uild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-21T09_31_50
_614Z-debug.log


> @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext-dsl-extens
ion
> yarn run clean && yarn run build

yarn run v1.12.3
$ rimraf lib
Done in 0.28s.
yarn run v1.12.3
$ tsc && yarn run copy-ls
src/browser/language-contribution.ts(30,12): error TS2339: Property 'languages'
does not exist on type 'typeof monaco'.
src/browser/language-contribution.ts(36,12): error TS2339: Property 'languages'
does not exist on type 'typeof monaco'.
src/browser/language-contribution.ts(52,12): error TS2339: Property 'languages'
does not exist on type 'typeof monaco'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

    at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\index.js:23
6:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:5572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 4)
(node:5572) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.


```

**Comment by svenefftinge** [comment]
merged

**Comment by githubaccccc** [comment]
remerged
